name: examen_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  mime: ^1.0.4
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  # flutter_web_plugins: ^0.1.0



  cupertino_icons: ^1.0.8
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - web/images/

